// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: course.proto

package course

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Duration int32

const (
	Duration_DURATION_UNSPECIFIED Duration = 0
	Duration_DURATION_15          Duration = 15
	Duration_DURATION_30          Duration = 30
	Duration_DURATION_60          Duration = 60
)

// Enum value maps for Duration.
var (
	Duration_name = map[int32]string{
		0:  "DURATION_UNSPECIFIED",
		15: "DURATION_15",
		30: "DURATION_30",
		60: "DURATION_60",
	}
	Duration_value = map[string]int32{
		"DURATION_UNSPECIFIED": 0,
		"DURATION_15":          15,
		"DURATION_30":          30,
		"DURATION_60":          60,
	}
)

func (x Duration) Enum() *Duration {
	p := new(Duration)
	*p = x
	return p
}

func (x Duration) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Duration) Descriptor() protoreflect.EnumDescriptor {
	return file_course_proto_enumTypes[0].Descriptor()
}

func (Duration) Type() protoreflect.EnumType {
	return &file_course_proto_enumTypes[0]
}

func (x Duration) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Duration.Descriptor instead.
func (Duration) EnumDescriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{0}
}

type Course struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProphetId     string                 `protobuf:"bytes,2,opt,name=prophet_id,json=prophetId,proto3" json:"prophet_id,omitempty"`
	Coursename    string                 `protobuf:"bytes,3,opt,name=coursename,proto3" json:"coursename,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Duration      Duration               `protobuf:"varint,6,opt,name=duration,proto3,enum=course.Duration" json:"duration,omitempty"`
	CreatedTime   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Course) Reset() {
	*x = Course{}
	mi := &file_course_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Course) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Course) ProtoMessage() {}

func (x *Course) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Course.ProtoReflect.Descriptor instead.
func (*Course) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{0}
}

func (x *Course) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Course) GetProphetId() string {
	if x != nil {
		return x.ProphetId
	}
	return ""
}

func (x *Course) GetCoursename() string {
	if x != nil {
		return x.Coursename
	}
	return ""
}

func (x *Course) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Course) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Course) GetDuration() Duration {
	if x != nil {
		return x.Duration
	}
	return Duration_DURATION_UNSPECIFIED
}

func (x *Course) GetCreatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTime
	}
	return nil
}

type CreateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProphetId     string                 `protobuf:"bytes,1,opt,name=prophet_id,json=prophetId,proto3" json:"prophet_id,omitempty"`
	Coursename    string                 `protobuf:"bytes,2,opt,name=coursename,proto3" json:"coursename,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Duration      Duration               `protobuf:"varint,5,opt,name=duration,proto3,enum=course.Duration" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseRequest) Reset() {
	*x = CreateCourseRequest{}
	mi := &file_course_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseRequest) ProtoMessage() {}

func (x *CreateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseRequest.ProtoReflect.Descriptor instead.
func (*CreateCourseRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCourseRequest) GetProphetId() string {
	if x != nil {
		return x.ProphetId
	}
	return ""
}

func (x *CreateCourseRequest) GetCoursename() string {
	if x != nil {
		return x.Coursename
	}
	return ""
}

func (x *CreateCourseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCourseRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateCourseRequest) GetDuration() Duration {
	if x != nil {
		return x.Duration
	}
	return Duration_DURATION_UNSPECIFIED
}

type CreateCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course        *Course                `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseResponse) Reset() {
	*x = CreateCourseResponse{}
	mi := &file_course_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseResponse) ProtoMessage() {}

func (x *CreateCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseResponse.ProtoReflect.Descriptor instead.
func (*CreateCourseResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCourseResponse) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

type GetCourseByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseByIDRequest) Reset() {
	*x = GetCourseByIDRequest{}
	mi := &file_course_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseByIDRequest) ProtoMessage() {}

func (x *GetCourseByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseByIDRequest.ProtoReflect.Descriptor instead.
func (*GetCourseByIDRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{3}
}

func (x *GetCourseByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCourseByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course        *Course                `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseByIDResponse) Reset() {
	*x = GetCourseByIDResponse{}
	mi := &file_course_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseByIDResponse) ProtoMessage() {}

func (x *GetCourseByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseByIDResponse.ProtoReflect.Descriptor instead.
func (*GetCourseByIDResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{4}
}

func (x *GetCourseByIDResponse) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

type ListCoursesByProphetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProphetId     string                 `protobuf:"bytes,1,opt,name=prophet_id,json=prophetId,proto3" json:"prophet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCoursesByProphetRequest) Reset() {
	*x = ListCoursesByProphetRequest{}
	mi := &file_course_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCoursesByProphetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCoursesByProphetRequest) ProtoMessage() {}

func (x *ListCoursesByProphetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCoursesByProphetRequest.ProtoReflect.Descriptor instead.
func (*ListCoursesByProphetRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{5}
}

func (x *ListCoursesByProphetRequest) GetProphetId() string {
	if x != nil {
		return x.ProphetId
	}
	return ""
}

type ListCoursesByProphetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courses       []*Course              `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCoursesByProphetResponse) Reset() {
	*x = ListCoursesByProphetResponse{}
	mi := &file_course_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCoursesByProphetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCoursesByProphetResponse) ProtoMessage() {}

func (x *ListCoursesByProphetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCoursesByProphetResponse.ProtoReflect.Descriptor instead.
func (*ListCoursesByProphetResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{6}
}

func (x *ListCoursesByProphetResponse) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

var File_course_proto protoreflect.FileDescriptor

const file_course_proto_rawDesc = "" +
	"\n" +
	"\fcourse.proto\x12\x06course\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfc\x01\n" +
	"\x06Course\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"prophet_id\x18\x02 \x01(\tR\tprophetId\x12\x1e\n" +
	"\n" +
	"coursename\x18\x03 \x01(\tR\n" +
	"coursename\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12,\n" +
	"\bduration\x18\x06 \x01(\x0e2\x10.course.DurationR\bduration\x12=\n" +
	"\fcreated_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vcreatedTime\"\xba\x01\n" +
	"\x13CreateCourseRequest\x12\x1d\n" +
	"\n" +
	"prophet_id\x18\x01 \x01(\tR\tprophetId\x12\x1e\n" +
	"\n" +
	"coursename\x18\x02 \x01(\tR\n" +
	"coursename\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12,\n" +
	"\bduration\x18\x05 \x01(\x0e2\x10.course.DurationR\bduration\">\n" +
	"\x14CreateCourseResponse\x12&\n" +
	"\x06course\x18\x01 \x01(\v2\x0e.course.CourseR\x06course\"&\n" +
	"\x14GetCourseByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x15GetCourseByIDResponse\x12&\n" +
	"\x06course\x18\x01 \x01(\v2\x0e.course.CourseR\x06course\"<\n" +
	"\x1bListCoursesByProphetRequest\x12\x1d\n" +
	"\n" +
	"prophet_id\x18\x01 \x01(\tR\tprophetId\"H\n" +
	"\x1cListCoursesByProphetResponse\x12(\n" +
	"\acourses\x18\x01 \x03(\v2\x0e.course.CourseR\acourses*W\n" +
	"\bDuration\x12\x18\n" +
	"\x14DURATION_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vDURATION_15\x10\x0f\x12\x0f\n" +
	"\vDURATION_30\x10\x1e\x12\x0f\n" +
	"\vDURATION_60\x10<2\x8b\x02\n" +
	"\rCourseService\x12I\n" +
	"\fCreateCourse\x12\x1b.course.CreateCourseRequest\x1a\x1c.course.CreateCourseResponse\x12L\n" +
	"\rGetCourseByID\x12\x1c.course.GetCourseByIDRequest\x1a\x1d.course.GetCourseByIDResponse\x12a\n" +
	"\x14ListCoursesByProphet\x12#.course.ListCoursesByProphetRequest\x1a$.course.ListCoursesByProphetResponseB2Z0github.com/wnmay/horo/shared/proto/course;courseb\x06proto3"

var (
	file_course_proto_rawDescOnce sync.Once
	file_course_proto_rawDescData []byte
)

func file_course_proto_rawDescGZIP() []byte {
	file_course_proto_rawDescOnce.Do(func() {
		file_course_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_course_proto_rawDesc), len(file_course_proto_rawDesc)))
	})
	return file_course_proto_rawDescData
}

var file_course_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_course_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_course_proto_goTypes = []any{
	(Duration)(0),                        // 0: course.Duration
	(*Course)(nil),                       // 1: course.Course
	(*CreateCourseRequest)(nil),          // 2: course.CreateCourseRequest
	(*CreateCourseResponse)(nil),         // 3: course.CreateCourseResponse
	(*GetCourseByIDRequest)(nil),         // 4: course.GetCourseByIDRequest
	(*GetCourseByIDResponse)(nil),        // 5: course.GetCourseByIDResponse
	(*ListCoursesByProphetRequest)(nil),  // 6: course.ListCoursesByProphetRequest
	(*ListCoursesByProphetResponse)(nil), // 7: course.ListCoursesByProphetResponse
	(*timestamppb.Timestamp)(nil),        // 8: google.protobuf.Timestamp
}
var file_course_proto_depIdxs = []int32{
	0, // 0: course.Course.duration:type_name -> course.Duration
	8, // 1: course.Course.created_time:type_name -> google.protobuf.Timestamp
	0, // 2: course.CreateCourseRequest.duration:type_name -> course.Duration
	1, // 3: course.CreateCourseResponse.course:type_name -> course.Course
	1, // 4: course.GetCourseByIDResponse.course:type_name -> course.Course
	1, // 5: course.ListCoursesByProphetResponse.courses:type_name -> course.Course
	2, // 6: course.CourseService.CreateCourse:input_type -> course.CreateCourseRequest
	4, // 7: course.CourseService.GetCourseByID:input_type -> course.GetCourseByIDRequest
	6, // 8: course.CourseService.ListCoursesByProphet:input_type -> course.ListCoursesByProphetRequest
	3, // 9: course.CourseService.CreateCourse:output_type -> course.CreateCourseResponse
	5, // 10: course.CourseService.GetCourseByID:output_type -> course.GetCourseByIDResponse
	7, // 11: course.CourseService.ListCoursesByProphet:output_type -> course.ListCoursesByProphetResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_course_proto_init() }
func file_course_proto_init() {
	if File_course_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_course_proto_rawDesc), len(file_course_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_course_proto_goTypes,
		DependencyIndexes: file_course_proto_depIdxs,
		EnumInfos:         file_course_proto_enumTypes,
		MessageInfos:      file_course_proto_msgTypes,
	}.Build()
	File_course_proto = out.File
	file_course_proto_goTypes = nil
	file_course_proto_depIdxs = nil
}
