package repository

import (
	"context"
	"time"

	"github.com/wnmay/horo/services/chat-service/internal/domain"
	repository_port "github.com/wnmay/horo/services/chat-service/internal/ports/outbound"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

type mongoMessageRepository struct {
	collection *mongo.Collection
}

func NewMongoMessageRepository(db *mongo.Database, collectionName string) repository_port.MessageRepository {
	collection := db.Collection(collectionName)

	return &mongoMessageRepository{
		collection: collection,
	}
}

func (r *mongoMessageRepository) SaveMessage(ctx context.Context, message *domain.Message) error {
	model := MessageModel{
		//ID auto-generated by Mongo
		RoomID:    message.RoomID,
		SenderID:  message.SenderID,
		Content:   message.Content,
		Type:      string(message.Type),
		Status:    string(message.Status),
		CreatedAt: time.Now(),
	}

	_, err := r.collection.InsertOne(ctx, model)
	return err
}

func (r *mongoMessageRepository) FindMessagesByRoomID(ctx context.Context, roomID string) ([]*domain.Message, error) {
	filter := bson.M{"room_id": roomID}
	cursor, err := r.collection.Find(ctx, filter, options.Find().SetSort(bson.D{{Key: "created_at", Value: 1}}))
	if err != nil {
		return nil, err
	}
	defer cursor.Close(ctx)

	var messages []*domain.Message
	for cursor.Next(ctx) {
		var msg domain.Message
		if err := cursor.Decode(&msg); err != nil {
			return nil, err
		}
		messages = append(messages, &msg)
	}

	if err := cursor.Err(); err != nil {
		return nil, err
	}

	return messages, nil
}
