package repository

import (
	"context"
	"time"

	"github.com/wnmay/horo/services/chat-service/internal/domain"
	outbound_port "github.com/wnmay/horo/services/chat-service/internal/ports/outbound"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

type mongoRoomRepository struct {
	client     *mongo.Client
	collection *mongo.Collection
}

func NewMongoRoomRepository(uri, dbName, collectionName string) (outbound_port.RoomRepositoryPort, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	client, err := mongo.Connect(ctx, options.Client().ApplyURI(uri))
	if err != nil {
		return nil, err
	}

	collection := client.Database(dbName).Collection(collectionName)

	return &mongoRoomRepository{
		client:     client,
		collection: collection,
	}, nil
}

func (r *mongoRoomRepository) FindRoomByID(ctx context.Context, roomID string) (*domain.Room, error) {
	objID, err := primitive.ObjectIDFromHex(roomID)
	if err != nil {
		return nil, err // invalid ObjectID string
	}

	filter := bson.M{"_id": objID}

	var room domain.Room
	if err := r.collection.FindOne(ctx, filter).Decode(&room); err != nil {
		return nil, err
	}
	return &room, nil
}

func (r *mongoRoomRepository) CreateRoom(ctx context.Context, room *domain.Room) (string, error) {
	model := RoomModel{
		//ID auto-generated by Mongo
		ProphetID:  room.ProphetID,
		CustomerID: room.CustomerID,
		CourseID:   room.CourseID,
		CreatedAt:  time.Now(),
	}
	res, err := r.collection.InsertOne(ctx, model)
	roomIDStr := res.InsertedID.(primitive.ObjectID).Hex()

	return roomIDStr, err
}
