// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/user_management.proto

package usermanagement

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_MapProphetNames_FullMethodName      = "/usermanagement.UserService/MapProphetNames"
	UserService_GetProphetName_FullMethodName       = "/usermanagement.UserService/GetProphetName"
	UserService_GetProphetIdsByNames_FullMethodName = "/usermanagement.UserService/GetProphetIdsByNames"
	UserService_MapUserNames_FullMethodName         = "/usermanagement.UserService/MapUserNames"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	MapProphetNames(ctx context.Context, in *MapProphetNamesRequest, opts ...grpc.CallOption) (*MapProphetNamesResponse, error)
	GetProphetName(ctx context.Context, in *GetProphetNameRequest, opts ...grpc.CallOption) (*GetProphetNameResponse, error)
	GetProphetIdsByNames(ctx context.Context, in *GetProphetIdsByNamesRequest, opts ...grpc.CallOption) (*GetProphetIdsByNamesResponse, error)
	MapUserNames(ctx context.Context, in *MapUserNamesRequest, opts ...grpc.CallOption) (*MapUserNamesResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) MapProphetNames(ctx context.Context, in *MapProphetNamesRequest, opts ...grpc.CallOption) (*MapProphetNamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MapProphetNamesResponse)
	err := c.cc.Invoke(ctx, UserService_MapProphetNames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetProphetName(ctx context.Context, in *GetProphetNameRequest, opts ...grpc.CallOption) (*GetProphetNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProphetNameResponse)
	err := c.cc.Invoke(ctx, UserService_GetProphetName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetProphetIdsByNames(ctx context.Context, in *GetProphetIdsByNamesRequest, opts ...grpc.CallOption) (*GetProphetIdsByNamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProphetIdsByNamesResponse)
	err := c.cc.Invoke(ctx, UserService_GetProphetIdsByNames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) MapUserNames(ctx context.Context, in *MapUserNamesRequest, opts ...grpc.CallOption) (*MapUserNamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MapUserNamesResponse)
	err := c.cc.Invoke(ctx, UserService_MapUserNames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	MapProphetNames(context.Context, *MapProphetNamesRequest) (*MapProphetNamesResponse, error)
	GetProphetName(context.Context, *GetProphetNameRequest) (*GetProphetNameResponse, error)
	GetProphetIdsByNames(context.Context, *GetProphetIdsByNamesRequest) (*GetProphetIdsByNamesResponse, error)
	MapUserNames(context.Context, *MapUserNamesRequest) (*MapUserNamesResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) MapProphetNames(context.Context, *MapProphetNamesRequest) (*MapProphetNamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MapProphetNames not implemented")
}
func (UnimplementedUserServiceServer) GetProphetName(context.Context, *GetProphetNameRequest) (*GetProphetNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProphetName not implemented")
}
func (UnimplementedUserServiceServer) GetProphetIdsByNames(context.Context, *GetProphetIdsByNamesRequest) (*GetProphetIdsByNamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProphetIdsByNames not implemented")
}
func (UnimplementedUserServiceServer) MapUserNames(context.Context, *MapUserNamesRequest) (*MapUserNamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MapUserNames not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_MapProphetNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapProphetNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).MapProphetNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_MapProphetNames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).MapProphetNames(ctx, req.(*MapProphetNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetProphetName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProphetNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetProphetName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetProphetName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetProphetName(ctx, req.(*GetProphetNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetProphetIdsByNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProphetIdsByNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetProphetIdsByNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetProphetIdsByNames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetProphetIdsByNames(ctx, req.(*GetProphetIdsByNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_MapUserNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapUserNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).MapUserNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_MapUserNames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).MapUserNames(ctx, req.(*MapUserNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "usermanagement.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MapProphetNames",
			Handler:    _UserService_MapProphetNames_Handler,
		},
		{
			MethodName: "GetProphetName",
			Handler:    _UserService_GetProphetName_Handler,
		},
		{
			MethodName: "GetProphetIdsByNames",
			Handler:    _UserService_GetProphetIdsByNames_Handler,
		},
		{
			MethodName: "MapUserNames",
			Handler:    _UserService_MapUserNames_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user_management.proto",
}
