// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: user_management.proto

package usermanagement

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirebaseToken string                 `protobuf:"bytes,1,opt,name=firebase_token,json=firebaseToken,proto3" json:"firebase_token,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_user_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_user_management_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetFirebaseToken() string {
	if x != nil {
		return x.FirebaseToken
	}
	return ""
}

func (x *RegisterRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *RegisterRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_user_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_user_management_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetClaimsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirebaseToken string                 `protobuf:"bytes,1,opt,name=firebase_token,json=firebaseToken,proto3" json:"firebase_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClaimsRequest) Reset() {
	*x = GetClaimsRequest{}
	mi := &file_user_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClaimsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClaimsRequest) ProtoMessage() {}

func (x *GetClaimsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClaimsRequest.ProtoReflect.Descriptor instead.
func (*GetClaimsRequest) Descriptor() ([]byte, []int) {
	return file_user_management_proto_rawDescGZIP(), []int{2}
}

func (x *GetClaimsRequest) GetFirebaseToken() string {
	if x != nil {
		return x.FirebaseToken
	}
	return ""
}

type GetClaimsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClaimsResponse) Reset() {
	*x = GetClaimsResponse{}
	mi := &file_user_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClaimsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClaimsResponse) ProtoMessage() {}

func (x *GetClaimsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClaimsResponse.ProtoReflect.Descriptor instead.
func (*GetClaimsResponse) Descriptor() ([]byte, []int) {
	return file_user_management_proto_rawDescGZIP(), []int{3}
}

func (x *GetClaimsResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetClaimsResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetClaimsResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_user_management_proto protoreflect.FileDescriptor

const file_user_management_proto_rawDesc = "" +
	"\n" +
	"\x15user_management.proto\x12\x0eusermanagement\"i\n" +
	"\x0fRegisterRequest\x12%\n" +
	"\x0efirebase_token\x18\x01 \x01(\tR\rfirebaseToken\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\",\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"9\n" +
	"\x10GetClaimsRequest\x12%\n" +
	"\x0efirebase_token\x18\x01 \x01(\tR\rfirebaseToken\"V\n" +
	"\x11GetClaimsResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role2\xb8\x01\n" +
	"\x15UserManagementService\x12M\n" +
	"\bRegister\x12\x1f.usermanagement.RegisterRequest\x1a .usermanagement.RegisterResponse\x12P\n" +
	"\tGetClaims\x12 .usermanagement.GetClaimsRequest\x1a!.usermanagement.GetClaimsResponseBBZ@github.com/wnmay/horo/shared/proto/usermanagement;usermanagementb\x06proto3"

var (
	file_user_management_proto_rawDescOnce sync.Once
	file_user_management_proto_rawDescData []byte
)

func file_user_management_proto_rawDescGZIP() []byte {
	file_user_management_proto_rawDescOnce.Do(func() {
		file_user_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_management_proto_rawDesc), len(file_user_management_proto_rawDesc)))
	})
	return file_user_management_proto_rawDescData
}

var file_user_management_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_user_management_proto_goTypes = []any{
	(*RegisterRequest)(nil),   // 0: usermanagement.RegisterRequest
	(*RegisterResponse)(nil),  // 1: usermanagement.RegisterResponse
	(*GetClaimsRequest)(nil),  // 2: usermanagement.GetClaimsRequest
	(*GetClaimsResponse)(nil), // 3: usermanagement.GetClaimsResponse
}
var file_user_management_proto_depIdxs = []int32{
	0, // 0: usermanagement.UserManagementService.Register:input_type -> usermanagement.RegisterRequest
	2, // 1: usermanagement.UserManagementService.GetClaims:input_type -> usermanagement.GetClaimsRequest
	1, // 2: usermanagement.UserManagementService.Register:output_type -> usermanagement.RegisterResponse
	3, // 3: usermanagement.UserManagementService.GetClaims:output_type -> usermanagement.GetClaimsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_management_proto_init() }
func file_user_management_proto_init() {
	if File_user_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_management_proto_rawDesc), len(file_user_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_management_proto_goTypes,
		DependencyIndexes: file_user_management_proto_depIdxs,
		MessageInfos:      file_user_management_proto_msgTypes,
	}.Build()
	File_user_management_proto = out.File
	file_user_management_proto_goTypes = nil
	file_user_management_proto_depIdxs = nil
}
